#!/bin/sh -e

BIN=""
if [ -d "venv" ] ; then
    BIN="venv/bin/"
fi

SOURCE_FILES="src tools"

set -x

${BIN}autoflake --in-place --recursive $SOURCE_FILES
${BIN}isort $SOURCE_FILES
${BIN}black --target-version=py39 $SOURCE_FILES
