resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: florimondmanca/azure-pipelines-templates
      ref: refs/tags/3.4

trigger:
  - master

pr:
  - master

variables:
  CI: true
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip

jobs:
  - template: job--python-check.yml@templates
    parameters:
      pythonVersion: "3.9"

  - template: job--python-test.yml@templates
    parameters:
      jobs:
        py39: null
